### PR TITLE
Changing default locales to better represent Linux users

### PR DESCRIPTION
**Pull request by der-eismann**
I found the default locales a bit weird, so I did some research what the biggst Linux users are. I know there can't be any reliable data, but [this was the best I found](http://www.linux-netbook.com/linux/linux-counter-map/) (using total users, not per capita). I also changed the order to be alphabetically, so nobody feels neglected - English is still on top 😄

### CODE REVIEW

**Comment by ikeydoherty** [comment]
And where are they getting their information from? And the languages should be sorted by commonality

**Comment by der-eismann** [comment]
Well... they take it from [registered users](https://www.linuxcounter.net/statistics). I don't really know how to measure commonality... I know that Germany is very active towards Linux, being German myself. I would at least swap it with Egypt, but apart from that, idk.
What did you use to create this first batch of default locales?
What's even the sense of ordering by commonality? You have the most common languages on the first page, the position shouldn't really matter. It's more important to find it quickly, so you would look at the letters, don't you think?

**Comment by der-eismann** [comment]
@ikeydoherty applied changes as discussed on IRC

**Comment by ikeydoherty** [comment]
ta

**Pull request merged**
